services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: iot-postgres
    restart: unless-stopped
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres123
       POSTGRES_DB: iot_rag
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: iot-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
